### ISSUE TITLE
ImportError: cannot import name array_tool ??

### ISSUE THREAD

**Issue by actionLUO** [chenyuntc/simple-faster-rcnn-pytorch#17]
How to solve this problem?

**Comment by chenyuntc** [comment]
Are you using Python2? try add `from __future__ import absolute_import`
arrary_tool is [in utils/array_tool.py](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/utils/array_tool.py)

**Comment by actionLUO** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-4-5a24dd2a2650> in <module>()
      4 import torch as t
      5 from utils.config import opt
----> 6 from model import FasterRCNNVGG16
      7 from trainer import FasterRCNNTrainer
      8 from data.util import read_image

/home/luoling/faster-rcnn/model/__init__.py in <module>()
----> 1 from .faster_rcnn_vgg16 import FasterRCNNVGG16

/home/luoling/faster-rcnn/model/faster_rcnn_vgg16.py in <module>()
      3 from torchvision.models import vgg16
      4 from model.region_proposal_network import RegionProposalNetwork
----> 5 from model.faster_rcnn import FasterRCNN
      6 from model.roi_module import RoIPooling2D
      7 from utils import array_tool as at

/home/luoling/faster-rcnn/model/faster_rcnn.py in <module>()
      3 import numpy as np
      4 import cupy as cp
----> 5 from utils import array_tool as at
      6 from model.utils.bbox_tools import loc2bbox
      7 from model.utils.nms import non_maximum_suppression

ImportError: cannot import name array_tool
I use python3!

**Comment by chenyuntc** [comment]
I've just tried, it worked fine in my server with `python 3.5.2`...
```Bash
python3 train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain
```

Temporary fix: copy `utils/array_tool.py` to `model/utils/` would fix for you. I will work on it to figure out why.

**Comment by chenyuntc** [comment]
I think you are using Python2, when I excute:
```Bash
python2 train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain
```
get the same error as you do:
```
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model import FasterRCNNVGG16
  File "model/__init__.py", line 1, in <module>
    from .faster_rcnn_vgg16 import FasterRCNNVGG16
  File "model/faster_rcnn_vgg16.py", line 5, in <module>
    from model.faster_rcnn import FasterRCNN
  File "model/faster_rcnn.py", line 5, in <module>
    from utils import array_tool as at
ImportError: cannot import name array_tool
```

**Comment by actionLUO** [comment]
I have solved the bug.  #[from .faster_rcnn_vgg16 import FasterRCNNVGG16]  from model/__init_
_.py and using (from model.faster_rcnn_vgg16 import FasterRCNNVGG16) instead of (from model import FasterRCNNVGG16).

**Comment by actionLUO** [comment]
@chenyuntc  I just use the  jupyter notebook demo. Not the train.py one.

**Comment by chenyuntc** [comment]
sorry, I can't reproduce it. I've just tried `demo.ipynb`, It still works fine for me :sob: 

Instead, when I changed it to pyhon2 kernel I get
```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4a4fda8ce59f> in <module>()
      4 import torch as t
      5 from utils.config import opt
----> 6 from model import FasterRCNNVGG16
      7 from trainer import FasterRCNNTrainer
      8 from data.util import  read_image

/home/cy/del/simple-faster-rcnn-pytorch/model/__init__.py in <module>()
----> 1 from .faster_rcnn_vgg16 import FasterRCNNVGG16

/home/cy/del/simple-faster-rcnn-pytorch/model/faster_rcnn_vgg16.py in <module>()
      3 from torchvision.models import vgg16
      4 from model.region_proposal_network import RegionProposalNetwork
----> 5 from model.faster_rcnn import FasterRCNN
      6 from model.roi_module import RoIPooling2D
      7 from utils import array_tool as at

/home/cy/del/simple-faster-rcnn-pytorch/model/faster_rcnn.py in <module>()
      4 import cupy as cp
      5 print('hhhh')
----> 6 from utils import array_tool as at
      7 from model.utils.bbox_tools import loc2bbox
      8 from model.utils.nms import non_maximum_suppression

ImportError: cannot import name array_tool
```
maybe there is a break in python, I'll try to figure why.

**Comment by brisker** [comment]
@chenyuntc 
is 4gb gpu enough？

**Comment by chenyuntc** [comment]
Yes, usually it's around 3GB. But some times it will raise to 4 GB  --- wired behaviour of CUPY.

**Comment by Xxxxxxxi** [comment]
hello,Have you solved this problem?I have same problem with python3.6..
